# Site settings
title: Dauren Amanbayev Blog
header-img: img/home-bg.jpg
email: itbook@inbox.ru
copyright_name: Dauren Amanbayev
description: "Personal blog of a Software & System Engineer about network observability, automation, and DevOps journey."
baseurl: "/blog"
url: "https://daurenamanbayev.github.io"

# Social Networks
github_username:  daurenamanbayev
linkedin_username: amanbayevdauren

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

plugins: [jekyll-paginate, jekyll-feed]